id: IE75E73E2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T03:37:47+00:00'
last_modified: '2022-06-07T12:11:01.954467+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS16918
  title: གསུང་འབུམ། ཤེས་རབ་རྒྱལ་མཚན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8794':
      image_group_id: I8LS16929
      title: Volume 1 of gsung 'bum/ shes rab rgyal mtshan/
      total_pages: 1346
      order: 1
      base_file: 8794.txt
    1EBC:
      image_group_id: I8LS16930
      title: Volume 2 of gsung 'bum/ shes rab rgyal mtshan/
      total_pages: 1155
      order: 2
      base_file: 1EBC.txt
    D470:
      image_group_id: I8LS16931
      title: Volume 3 of gsung 'bum/ shes rab rgyal mtshan/
      total_pages: 1196
      order: 3
      base_file: D470.txt
    45EF:
      image_group_id: I8LS16932
      title: Volume 4 of gsung 'bum/ shes rab rgyal mtshan/
      total_pages: 1042
      order: 4
      base_file: 45EF.txt
    B700:
      image_group_id: I8LS16933
      title: Volume 5 of gsung 'bum/ shes rab rgyal mtshan/
      total_pages: 992
      order: 5
      base_file: B700.txt
    5BD8:
      image_group_id: I8LS16934
      title: Volume 6 of gsung 'bum/ shes rab rgyal mtshan/
      total_pages: 962
      order: 6
      base_file: 5BD8.txt
    '8685':
      image_group_id: I8LS16935
      title: Volume 7 of gsung 'bum/ shes rab rgyal mtshan/
      total_pages: 1390
      order: 7
      base_file: 8685.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
